# 把 src/js/*.js 转成 C 字符串数组。输入目录、输出路径由调用方传入。
function(tb_embed_js IN_DIR OUT_FILE)
  file(GLOB TB_JS_SRC ${IN_DIR}/*.js)
  list(SORT TB_JS_SRC)
  set(LINES "")
  foreach(f ${TB_JS_SRC})
    file(READ ${f} SRC)
    string(REPLACE "\\" "\\\\" SRC "${SRC}")
    string(REPLACE "\"" "\\\"" SRC "${SRC}")
    string(REPLACE "\n" "\\n" SRC "${SRC}")
    get_filename_component(base ${f} NAME)
    string(APPEND LINES "  /* ${base} */\n  \"${SRC}\",\n")
  endforeach()
  file(WRITE ${OUT_FILE} "/* 由 cmake/embed_js.cmake 生成,勿手改。 */\nconst char *const tb_js_builtins[] = {\n${LINES}  NULL\n};\n")
endfunction()
